### PR TITLE
Look through interfaces and pointers when determining emptiness

### PR DESCRIPTION
**Pull request by novas0x2a**
When dealing with map[string]interface{}, the common case for loading
arbitrary data from yaml/json, empty strings are not overwritten because
they appear as a non-empty interface containing an empty string. This
change causes non-nil interfaces to be examined for emptiness.

### CODE REVIEW

**Comment by imdario** [comment]
I'll check this later. Thanks.

**Comment by imdario** [comment]
PR #81 was merged instead of this after checking they were very similar. I checked your test against it and it doesn't seem to work yet. If you can check it too, we can fix both issues.

**Comment by novas0x2a** [comment]
I changed my test to match the convention, and updated my pr to not conflict with the current code. (I also deleted the duplicate test, because I couldn't run the test without doing so).

**Comment by imdario** [comment]
Done. Thanks!

**Pull request merged**
