### PR TITLE
Do not panic on private map properties

### PR DESCRIPTION
**Pull request by idrarig**

### CODE REVIEW

**Comment by imdario** [comment]
Good one. Just two questions:

- [CanInterface actullay panics if IsValid returns false](https://golang.org/src/reflect/value.go?s=29894:29923#L888). Shouldn't we use IsValid instead?
- In case of CanInterface is actually better than IsValid for our use case, should we use it at the beginning of the method instead of IsValid?

Thanks!

**Comment by idrarig** [comment]
Hi!, thanks for your feedback!

At the point where I inserted the call to `CanInterface()` we are sure that it's valid, because you check for it at line 45.

I tried to study and experiment with the code a little bit to better understand and address your questions, but I'm a bit worried about the fact that commenting out the checks at lines 19-21 and 45-47 doesn't break any test. Is it because those checks are really superfluous or because we need more tests?...

**Comment by imdario** [comment]
You are right, CanInterface() is right where you call it. I didn't remember the previous IsValid.

About the check at lines 19-21 and 45-47: I think Mergo should be defensive about its input because it must handle any possible scenario. As you found, I didn't think about private map properties.

So, your PR looks good to me. Don't worry about my questions as I missed the check at 45-47 and they don't make sense anymore.

Merging your PR in one minute.

**Comment by idrarig** [comment]
Thanks!

**Pull request merged**
