### PR TITLE
Fix merging of interface types with concrete values

### PR DESCRIPTION
**Pull request by admtnnr**

### CODE REVIEW

**Comment by vdemeester** [comment]
@admtnnr Thanks for the PR. Can you describe a bit more why is this needed (which use cases, …) ?

**Comment by admtnnr** [comment]
@vdemeester sure, here's the case I ran into:
Say we have an interface:
```go
type Doer interface {
  Do() error
}
```
And we have two implementations of that interface:
```go
type NoopDoer string
func (d NoopDoer) Do() error { return nil }

type RealDoer struct { ... }
func (d RealDoer) Do() error {
  ...
  return nil
}
```
And we have our config struct like so:
```go
type config struct {
   Doer Doer 
}
```
And we set up a "default" config that we will merge in that uses the `NoopDoer` we defined above:
```go
var defaultConfig = config{
  Doer: NoopDoer("this does nothing"),
}
```
What I've encountered is that the call to `mergo.Merge` fails if you have a setup where you pass in a config that also has a `Doer` defined that should take precedence, *but is a different concrete type*.
So something like this will return an error and panic where it shouldn't since the config should accept any implementation of a `Doer`:
```go
var myConfig = config{
  Doer: RealDoer{},
}
if err := mergo.Merge(&myConfig, defaultConfig); err != nil {
   panic("THIS WILL GET RUN")
}
```
So what actually seems to happen is that `mergo` doesn't check that the types are actually assignable to the field in the struct, but rather just checks that the source and destination types are the same.

It skips through this case since the underlying types aren't the same: https://github.com/imdario/mergo/pull/106/files#diff-a103b5fee5fb31abebf12ee067c01da8R190 and instead hits this line: https://github.com/imdario/mergo/pull/106/files#diff-a103b5fee5fb31abebf12ee067c01da8R195

The test I added will fail if the check for `AssignableTo` is removed even though both types implement `http.Handler`.

Hopefully that helps explain it a little better. It's a weird case, I'll give you that. :)

**Comment by vdemeester** [comment]
> So what actually seems to happen is that `mergo` doesn't check that the types are actually assignable to the field in the struct, but rather just checks that the source and destination types are the same.

@admtnnr indeed :sweat_smile:

**Comment by vdemeester** [comment]
@admtnnr btw can you rebase against master to fix the CI ? :angel:

**Comment by admtnnr** [comment]
@vdemeester Rebased.

**Comment by admtnnr** [comment]
@vdemeester let me know if there's anything else you need from me to get this merged. :)

**Pull request merged**
