### PR TITLE
Fix merge of sub map stored in a map[]interface{}

### PR DESCRIPTION
**Pull request by pijalu**
See https://github.com/micro/go-config/issues/18

This PR should fix map[]interface{} containing maps

### CODE REVIEW

**Comment by asim** [comment]
@imdario any interest in this patch?

**Comment by imdario** [comment]
I'll check it later today. Thanks.

**Comment by pijalu** [comment]
Hi,
It's nearly the same but I don't check for isEmptyValue(dst) as I think that should be covered with isEmptyValue(dstElement)

Note: I was also running into the same bug, but saw the PR for that after

**Comment by asim** [comment]
Any update on merging this PR?

**Comment by imdario** [comment]
Let me check it again and see which one will leave the thunderdome.

**Comment by imdario** [comment]
Done.

**Pull request merged**
