### PR TITLE
Added code to run o power systems

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by genisysram** [comment]
@bionoren
please merge my pull request.

**Comment by bionoren** [comment]
@genisysram This isn't my repository and I don't have commit access. You'll need to ask someone else to merge this pull request.

**Comment by genisysram** [comment]
@imdario 
hey hii
Please merge my PR !!

**Review by imdario — APPROVED** [review]

**Comment by imdario** [comment]
@genisysram Done. Sorry, I wasn't able to merge it before.

**Pull request merged**
